# Generated by Django 5.2.3 on 2025-06-16 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='conteudo_detalhado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceito',
            name='explicacao_detalhada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='topicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('solucao', models.TextField(blank=True, null=True)),
                ('aula_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.aula')),
            ],
        ),
    ]
